# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
jobs:
  mybuild:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            curl -X POST -H"Content-Type:application/json" -H"Authorization:env.DEVSCORE_WEBHOOK_SECRET" -d @/tmp/webhook.json "env.DEVSCORE_WEBHOOK_ENDPOINT"
workflows:
  version: 2
  my-workflow:
    jobs:
      - mybuild:
        context: devscore


